spring.application.name=Template Service

# DB Connection

spring.datasource.url=jdbc:postgresql://ep-calm-sky-anraoghy-pooler.c-6.us-east-1.aws.neon.tech/notification_service
spring.datasource.username=neondb_owner
spring.datasource.password=npg_QJeGw5npb4Ba

# Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none

# Show SQL (disable in prod)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true